### ISSUE TITLE
Number parser does not include 0!

### ISSUE THREAD

**Issue by HMarzban** [lukeed/mri#9] opened 2019-04-09 18:30 UTC
```javascript
const mri = require("mri")

console.log(mri(['--bar= 132568])) // { _: [], bar: 132568 }  TRUE   
console.log(mri(['--bar= 0132568])) // { _: [], bar: 132568 }  FALSE
console.log(mri(['--bar= "0132568"])) // { _: [], bar: 132568 } FALSE
```
as an example, number `zero` does not include in,  even when I put a number in double quotations, `mri`  convert the string to a number and this converting omit zero!

**Comment by HMarzban** [comment] 2019-04-09 18:37
![image](https://user-images.githubusercontent.com/20157508/55825944-2a653b00-5b1c-11e9-84d2-f21ae97cec12.png)

**Comment by lukeed** [comment] 2019-04-09 18:37
Hmm... so this is because `mri` converts to numbers. It actually _does_ accept zero (eg, `--bar 0`), but in this particular case, it's because `Number("0132568")` _is_ `132568`

**Comment by lukeed** [comment] 2019-04-09 18:39
Ah, so if you _know_ it's going to be `--bar` (or `--password` in this case) you should use the `string` option. That's the only way to override/prevent the typecasting from happening.

```js
mri(['--bar=0132568'], { 
  string: ['bar']
});
//=> { _: [], bar: '0132568' }

**Comment by lukeed** [comment] 2019-04-09 19:08
Closing this since it's working as designed. Any `Number` parsing will always remove preceding zeros – they can only remain when the number exists as a string.

So, in this particular case, you have to _opt out_ of `mri`'s Number parsing, and that's achievable thru the snippet above.

Hope that helps, but please follow up if you need to!
Thanks~!

**Closed by lukeed** 2019-04-09 19:08 UTC
